# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM
   syntax_highlighter: rouge

gems: [jekyll-sitemap, jekyll-paginate, jekyll-seo-tag]

exclude: [vendor]

# Permalinks
permalink: /:title/

# Site
title: 'Swift Weekly Brief'
description: 'A community-driven weekly newsletter about Swift.org'
url: https://swiftweekly.github.io
logo: /img/logo.png
timezone: America/Los_Angeles

handle: '@swiftlybrief'

curator:
  name: 'Jesse Squires'
  url: https://twitter.com/jesse_squires

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
  twitter: 'https://twitter.com/swiftlybrief'
  github: 'https://github.com/SwiftWeekly/swiftweekly.github.io'
  issue: 'https://github.com/SwiftWeekly/swiftweekly.github.io/issues/new'
  pull: 'https://github.com/SwiftWeekly/swiftweekly.github.io/compare'
